Add reader for gridded AHI data
pytroll/satpy pull request #1312
Opened 2020-08-13 15:34 UTC by simonrp84

This PR adds the ability to read Himawari/AHI data in the gridded format provided by [Chiba University](http://www.cr.chiba-u.jp/databases/GEO/H8_9/FD/index_jp.html).

The gridded data is in flat binary format and, to my knowledge, only comes for the full disk and not the `JP` or `R0` subsets. Data comes as digital counts and requires external look-up tables in order to convert into reflectance or brightness temperature. This reader checks if these LUTs are available and, if not, downloads them.

Note: Tests TBD. I want to see what your opinions are on the reader code before I write tests for something that might change.

2020-08-13 15:45 UTC, mraspaud commented on satpy/readers/ahi_grid.py
> +        shutil.rmtree(tdir + '/count2tbb/')
Please use `os.path.join` for assembling paths, it makes the code more os-independent

2020-08-24 08:19 UTC, mraspaud requested changes
Nice PR, where you make a nice reader out of an ugly format! I have some inline comments, mostly about the last test case.

2020-08-24 08:19 UTC, mraspaud commented on satpy/readers/ahi_gridded.py
> +            raise FileNotFoundError("No LUT file found:", lut_file)
This could become a separate method, eg `_get_lut`

2020-08-24 08:19 UTC, mraspaud commented on satpy/readers/ahi_gridded.py
> +        """LUTs are stored on an FTP server, this function downloads them."""
docstrings should start with a verb in imperative mood.

2020-08-24 08:19 UTC, mraspaud commented on satpy/readers/ahi_gridded.py
> +        """Downloaded LUTs are a compressed tarball, uncompress here."""
docstrings should start with a verb in imperative mood.

2020-08-24 08:19 UTC, mraspaud commented on satpy/readers/ahi_gridded.py
> +        """LUTs are needed for count->REFL/BT conversion. Download them."""
docstrings should start with a verb in imperative mood.

2020-08-24 08:19 UTC, mraspaud commented on satpy/readers/ahi_gridded.py
> +        logger.debug("Reading time " + str(datetime.now() - tic))
I know this is present in multiple reader, but I think it should be phased out, since the lazy reading makes this irrelevant...

2020-08-24 08:19 UTC, mraspaud commented on satpy/readers/ahi_gridded.py
> +        logger.debug("Calibration time " + str(datetime.now() - tic))
Same here, I don't think the timing is relevant anymore.

2020-08-24 08:19 UTC, mraspaud commented on satpy/tests/reader_tests/test_ahi_gridded.py
> +        self.assertEqual(tmp_fh.area.proj_str, good_area.proj_str)
Would it work to replace these with asserting the equality between `tmp_fh.area` and `good_area` ? (ie delegating the comparison to the area object)

2020-08-24 08:19 UTC, mraspaud commented on satpy/tests/reader_tests/test_ahi_gridded.py
> +        mocks[3].assert_called()
This test just checks that `_untar_luts` and `_download_luts` are called. To check that the lut download operates successfully, shouldn't we be checking that a downloaded tar file is correctly untarred and place in the right directory?

2020-08-24 08:19 UTC, mraspaud commented on satpy/tests/reader_tests/test_ahi_gridded.py
> +class TestAHIGriddedLUTs(unittest.TestCase):
Ok, I think this testcase need to become a bit more concrete that just checking if some functions are called.

I would propose mocking the ftplib so as to create a dummy tar file (on the fly) in a given directory and then check that then other functions really do untar, remove, etc.

2020-09-09 10:28 UTC, mraspaud approved these changes

2020-09-09 10:28 UTC, merged

2020-09-09 13:11 UTC, djhoese commented
Sorry I didn't see this earlier, but this reader's name does not conform to the reader naming convention.

2020-09-09 13:13 UTC, mraspaud commented
...and the reader needs to be added to the reader list in the documentation's first page... Sorry about the sloppy review.

2020-09-09 13:31 UTC, simonrp84 commented
*restores branch