Only add longitude/latitude variables in cf_writer if they are not included already.
pytroll/satpy pull request #1357
Opened 2020-09-10 13:32 UTC by ninahakansson

Only add lon/lat variables if they are not included already.
Level1c4pps ended up with both lat/lon and latitude/longitude coordinates.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [x] Passes ``flake8 satpy``

2020-09-10 14:01 UTC, mraspaud commented on satpy/writers/cf_writer.py
> +    if ('lat' in dataarray and 'lon' in dataarray) or ('latitude' in dataarray and 'longitude' in dataarray):
To make this clearer, could we have `if ('lat' in dataarray.coords and...`?

2020-09-10 14:02 UTC, mraspaud commented
@ninahakansson Thanks for adding this. Do you know where the `lon` and `lat` variants are coming from? afaik we use the full `longitude` and `latitude` names in satpy.

2020-09-10 14:34 UTC, ninahakansson commented
The lat/lon is from level1c4pps and from PPS.  So in one way they do not belong here I guess. We have the include_lonlats attribute that in level1c4pps is set to False to avoid adding lat/lons again. But in area2cf this attribute is ignored if the data is in Swath definition. This line: 
```if isinstance(dataarray.attrs['area'], SwathDefinition) or strict:```
Changing the or => and would also solve my problem. But I am afraid that would break something for other users.

2020-09-11 09:38 UTC, mraspaud commented
@ninahakansson changing `or` with `and` would change the meaning of this. `strict` means that we want to include lons/lats even if there is a valid grid mapping.

2020-09-15 12:29 UTC, mraspaud requested changes
Good start. I'm missing a test that describe your use case, with the renaming of the coordinates. Maybe that would be testing the `_collect_datasets` function?

2020-09-15 12:29 UTC, mraspaud commented on satpy/tests/writer_tests/test_cf.py
> +    def test_dataset_is_projection_coords(self):
Can you make a separate test case for these two test methods? they have a lot of test data in common which you can then refactor into the `setUp` method of the test case

2020-09-16 13:07 UTC, mraspaud approved these changes
LGTM, thanks for fixing the lon/lat overwrite!

2020-09-16 13:10 UTC, mraspaud commented
@sfinkens do you want to check this against pygac-fdr before I merge this?

2020-09-16 14:49 UTC, sfinkens commented
No, go ahead! I'll see what the system tests will find.

2020-09-16 15:16 UTC, merged