BUG FIX:  issue1387 changing date string formats from NUCAPS requires…
pytroll/satpy pull request #1388
Opened 2020-10-02 19:34 UTC by joleenf

… a more flexible approach to creating a datetime object, use pandas.to_datetime().to_pydatetime() for this.

NUCAPS data has multiple ways of writing the date string in the file, try to use pandas.to_datetime to minimize the risk ValueError when reading the date string from the NUCAPS file.

 - [ ] Closes #1387

2020-10-04 13:53 UTC, djhoese approved these changes
Like I mentioned on slack, this is less explicit but more flexible. It is a different approach than we normally take but pandas is a hard requirement for xarray so I'm ok with this.

2020-10-06 04:25 UTC, mraspaud requested changes
Nice with pandas helping out here. Could you add a few tests checking that the problematic date formats you encountered are handled properly?

2020-10-06 12:06 UTC, joleenf commented
I have two questions:  1.)  Is there a way to just add a second test within the test_nucaps.py code to test for both date formats?  I suspect this is true, but I don't immediately see how that would run.  2.)  In February 2020, it looks like the method for calling the test suite has changed (7945a805), will any tests added to the reader_tests directory run without any addition to other __init__ files in the directory or elsewhere?

2020-10-06 13:13 UTC, djhoese commented
1. Although unrealistic, the easiest thing could be to have start time in one format in test_nucaps.py and end time in another format. Another option would be to have some special case in the `FakeNetCDF4FileHandler2` in `test_nucaps.py`. Like if the date for the filename provided is greater than January 2020, put start and end time in format X otherwise format Y.

2. We are using pytest now which should discover all the tests so no need to modify `__init__.py`.

2020-10-16 11:28 UTC, joleenf commented
The test dates for start_time and end_time, are currently defined as 
```
file_content = { 
    'attr/time_coverage_start': filename_info['start_time'].strftime('%Y-%m-%dT%H:%M:%S.%fZ'),
    '/attr/time_coverage_end': filename_info['end_time'].strftime('%Y-%m-%dT%H:%M:%SZ'),
    etc...}
```

However, it seems like can't really be testing how the reader is interpreting the data in a real file.  So I am thinking that a better test is 
```
file_content = { 
    '/attr/time_coverage_start': "2020-10-20T12:00:00.5Z",
    '/attr/time_coverage_end': "2020-10-20T12:00:36Z",
    etc...}
```
Correct?  I can check in a new version if that is correct.

2020-10-16 11:54 UTC, djhoese commented
Not sure I understand. Isn't the end result (a date formatted as a string) the same?

2020-10-16 12:13 UTC, joleenf commented
Yes.  I am just thinking that if I am trying to test if the reader will correctly read the actual data file, I shouldn't define the test data as a datetime object, rather as a string like it appears in the nucaps file.

2020-10-16 12:25 UTC, djhoese commented
Sounds good. I mean they are both strings but yeah strftime couldn't be making the string more acceptable than nucaps might be making it. Commit away!

2020-11-05 13:23 UTC, djhoese commented
Tests have been added and all requested changes seem complete. Merging now. Thanks again @joleenf!

2020-11-05 13:23 UTC, merged