Updated nwcsaf yaml reader
pytroll/satpy pull request #2048
Opened 2022-03-08 13:12 UTC by ninahakansson

PPS-2021 CMIC dataset cmic_cre correspond to PPS-2018 CPP dataset cpp_reff.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

2022-03-10 08:33 UTC, mraspaud requested changes
Looks like this logic will work, nice job! Tests are missing though :)

2022-03-10 08:33 UTC, mraspaud commented on satpy/readers/nwcsaf_nc.py
> +            variable = self.nc[file_keys[1]]
Should there be a loop here, as we can't be sure there will be only 2 items?

2022-03-10 08:33 UTC, mraspaud commented on satpy/readers/nwcsaf_nc.py
> +                    so_dataset = self.nc[self.file_key_prefix + info['scale_offset_dataset'][1]]
This looks very similar to the code above, could these lines be factorised together somehow?

2022-03-10 08:33 UTC, mraspaud commented on satpy/etc/readers/nwcsaf-pps_nc.yaml
> +
This can be removed

2022-03-10 20:13 UTC, mraspaud requested changes
Looks good, now just tests missing.

2022-03-25 09:14 UTC, mraspaud commented on satpy/tests/reader_tests/test_nwcsaf_nc.py
> +        self.fh.nc["cmic_cre"] = the_array
```suggestion
        data_array = xr.DataArray(np.ones((5, 10)), attrs={"scale_factor": np.array(scale, dtype=float),
                                                           "add_offset": np.array(offset, dtype=float)})

        self.fh.nc["cpp_reff"] = data_array
        self.fh.nc["cmic_cre"] = data_array
```

2022-03-25 09:15 UTC, mraspaud approved these changes
LGTM, just one naming suggestion

2022-03-30 09:11 UTC, adybbroe reviewed
I just have one question. LGTM otherwise

2022-03-30 10:51 UTC, adybbroe commented
@mraspaud I accidentally requested you to re-review this. But now that I bothered you,p what should we do with the failed tests above? They don't seem to have anything to with the PR here? Perhaps you need to merge latest main into your PR branch @ninahakansson ?

2022-03-30 10:53 UTC, mraspaud commented
These errors seem to come from third party libraries. Someone should look up that error and maybe report a bug to them if necessary to get it fixed.

2022-03-30 10:53 UTC, mraspaud commented
I can try to have a look at it this afternoon

2022-04-07 18:45 UTC, adybbroe approved these changes
LGTM

2022-04-08 06:12 UTC, mraspaud commented
I just merge main into this to fix the CI

2022-04-08 07:49 UTC, merged