Add 'use_map_blocks' to `apply_enhancement` utility function
pytroll/satpy pull request #2133
Opened 2022-06-25 15:27 UTC by djhoese

I've wanted to do this for a while. Some enhancements require multiple numpy/dask function calls which each produce their own dask task. This is unnecessary in most cases and makes debugging more difficult since you don't know if all the tasks are related. It also results in a small overhead from dask itself due to processing each task.

This PR adds a `use_map_blocks` keyword argument to the `apply_enhancement` function used by a lot of builtin satpy enhancements so that they can use dask's `map_blocks` to make one dask task instead of many little tasks. I didn't add tests when doing this as it started out as just a refactor (require a switch to using map_blocks) but then I realized someone may need to not use map_blocks so I added the kwarg.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [x] Fully documented

2022-07-29 08:14 UTC, gerritholl commented
What is the status of this PR?  What would still need to be done?

2022-07-29 14:15 UTC, djhoese commented
@gerritholl this mostly needs a review from the various people that might care. There is enough refactoring that a "clean code" review would be good, but otherwise this shouldn't change the end result of things. This does change the default processing path for enhancements using this helper method and passing dask arrays. If their functions don't expect per-chunk arrays then they might need to change things...but for the tests we have for the builtin enhancements it seems we're good.

2022-08-05 08:47 UTC, mraspaud requested changes
I'm fine with functionality and logic. However, I think the number of arguments to apply_enhancement is starting to bug me. From what I see, the past last keywords (separate, pass_dask, use_mapblock) are actually predefined per enhancement, so my bet is that the code would be much cleaner if we turned them into decorators to use on each individual enhancement function. This will make each function accept a full dask array once decorated.
I'm going to try implementing is and making a PR to your PR, see if you like it.

2022-08-05 18:00 UTC, mraspaud approved these changes
LGTM

2022-08-05 18:01 UTC, merged