Fix cf write-read roundtrip
pytroll/satpy pull request #2176
Opened 2022-08-15 14:24 UTC by mraspaud

This PR fixes the sensor reading from satpy-written cf files.

 - [ ] Closes #2170  
 - [x] Tests added

2022-08-15 14:37 UTC, djhoese requested changes
The fix looks good to me. Did you mean to commit the viirs compact tests refactor?

Can the new CF test please be added to the reader tests? If I'm working on the reader or writer I'm not going to think to look in this completely separate module for a test. Granted it will fail when all the tests are run either way, but that will happen if it is in the reader tests too.

2022-08-15 14:37 UTC, djhoese commented on satpy/tests/test_cf_roundtrip.py
> +# -*- coding: utf-8 -*-
Do we maybe want to start not including these in new modules given the conversation in pyresample with @gerritholl?

2022-08-15 15:54 UTC, mraspaud commented
Yes the viirs compact refractor is to create the fixtures that we then use in the round-trip test.

2022-08-29 12:08 UTC, djhoese commented
> Can the new CF test please be added to the reader tests? If I'm working on the reader or writer I'm not going to think to look in this completely separate module for a test. Granted it will fail when all the tests are run either way, but that will happen if it is in the reader tests too.

@mraspaud what were you thoughts on this comment of mine? Any time to work on it this week? This should then make @BENR0's #1695 clearer.

2022-08-29 12:32 UTC, mraspaud commented
Yes, I'm looking at it right now.

2022-08-29 12:58 UTC, mraspaud commented
As per the conversation on slack, @djhoese is good with leaving the roundtrip test in its own module.

2022-08-29 12:58 UTC, merged

2022-08-29 13:05 UTC, djhoese commented
>  @djhoese is good with leaving the roundtrip test in its own module.

For the record I'm not, but I don't want to waste people's time discussing it. In the grand scheme of things it isn't that big of a deal.