Add an argument to the compositor to switch alpha band on/off in DayNightCompositor
pytroll/satpy pull request #2358
Opened 2023-01-19 12:02 UTC by yukaribbba

This PR is a solution for #2357. It only takes effect in "day only" or "night only" mode.

 - [ ] Closes #xxxx 
 - [ ] Tests added 
 - [ ] Fully documented 
 - [ ] Add your name to `AUTHORS.md` if not there already

2023-01-19 15:07 UTC, djhoese requested changes
I have one inline change to say `include_alpha` instead of `need_alpha`, but otherwise I have one other question/suggestion:

What if you forced the other data to be NaN in this case instead of `0` (like it is now)? This would mean you'd have to specify `fill_value=0` on your `save_datasets` call, but I think this is more inline with other composites that Satpy produces...maybe? Put another way, the alpha band would be added during `save_datasets` rather than in the compositor.

2023-01-19 15:07 UTC, djhoese commented on satpy/composites/__init__.py
> +                               False means the output is just a single-band image with masked-out area
I'm not sure how I feel about the word "need" here. I think to go along with other similar keyword arguments in Satpy, could we call this `include_alpha`?

```suggestion
            include_alpha (bool): This only affects the "day only" or "night only" result.
                               True means an alpha band will be added to the output image for transparency.
                               False means the output is a single-band image with undesired pixels being masked out (replaced with NaNs).
```

The above change reflects my other suggestion in my review comment.

2023-01-19 15:19 UTC, yukaribbba commented
> I have one inline change to say `include_alpha` instead of `need_alpha`, but otherwise I have one other question/suggestion:
> 
> What if you forced the other data to be NaN in this case instead of `0` (like it is now)? This would mean you'd have to specify `fill_value=0` on your `save_datasets` call, but I think this is more inline with other composites that Satpy produces...maybe? Put another way, the alpha band would be added during `save_datasets` rather than in the compositor.

Yeah I tried that before but didn't work out so I turned to the compositor. It will force an alpha band added to the image and I think that's the reason. Only when it turned off the `fill_value=0` has the effect.

2023-01-19 15:53 UTC, djhoese commented
> Yeah I tried that before but didn't work out so I turned to the compositor. It will force an alpha band added to the image and I think that's the reason. Only when it turned off the fill_value=0 has the effect.

Sorry I wasn't clear. I understand that the existing way the compositor work wasn't working as it was always adding an alpha band. What I'm suggesting is that in this compositor it currently replaces the masked data with 0 making it black. I think when this alpha flag is `False` that this should instead be `np.nan` so that the result of the compositor is still a single band, but the unwanted data is NaN instead of 0. This, by default, will produce an alpha band in the geotiff writer, but if you specify `fill_value=0` in `Scene.save_datasets` it should become black. Since the compositor isn't creating the Alpha band this should work.

2023-01-19 16:21 UTC, djhoese commented
Yeah I think that would work. It might also work to just replace 0 with `np.nan` since in the Alpha case those would be masked/transparent anyway.

2023-01-19 16:27 UTC, yukaribbba commented
> Yeah I think that would work. It might also work to just replace 0 with `np.nan` since in the Alpha case those would be masked/transparent anyway.

Got it. I’ll finish it tomorrow. Heading to bed now.😁

2023-01-20 03:11 UTC, yukaribbba commented
> Yeah I think that would work. It might also work to just replace 0 with `np.nan` since in the Alpha case those would be masked/transparent anyway.

I tried replacing `0` with `np.nan` in these two lines. However I always got both night and day portions masked-out despite other arguments. So I had to send it back to 0. I had several tests under the latest commit and it worked perfectly for me. You can see the upper left one is just what I need.
![image](https://user-images.githubusercontent.com/72339781/213609695-dbfbe5c1-b41b-468c-bb2d-5834afdaa44c.png)

2023-01-20 03:18 UTC, djhoese commented
Ah it is because the merging of the day and the night is a multiply and an addition:

https://github.com/pytroll/satpy/blob/fc99734024b3c8a029cc071b5cf5b8b35eac19e4/satpy/composites/__init__.py#L750

Doing that with NaN is not going to work. Hhhmm I'm about to go to sleep. I'll have to think about this more.

2023-01-20 05:43 UTC, yukaribbba commented
What about this? We send `np.nan` to coszen instead of the data itself, keeping the data at 0, and we can also make `data = night_portion + day_portion` safe.

For example, if coszen is a numpy array:
```
if "only" in self.day_night:
    if "day" in self.day_night:
        coszen[np.where(coszen == 0)] = np.nan # This will make the night portion coszen np.nan and keep day portion original 
    else:
        coszen[np.where(coszen == 1)] = np.nan # This will make the day portion coszen np.nan and keep night portion original
```

But I don't know how to do that in dask....

2023-01-20 11:02 UTC, yukaribbba commented
And the test results:
![image](https://user-images.githubusercontent.com/72339781/213679668-d2e97ed2-3419-48c2-8365-44070dccc9f5.png)
You can see the last one is a little different from above. Since the night portion pixels are replaced with NaN, this area is considered as outter space. This is like what you said I suppose.

2023-01-20 14:24 UTC, yukaribbba commented
Whoops…

2023-01-20 14:25 UTC, djhoese commented
The difference you're talking about is how the bottom-right case doesn't "fade" into night time like the alpha=True cases, right? Yeah I think this makes sense. I'm not sure if it will be expected by all users but I think it is the only option if you don't want an alpha channel and also want only day(night) data.

@mraspaud @pnuu @gerritholl any opinions on this?

2023-01-20 14:28 UTC, yukaribbba commented
>  I'm not sure if it will be expected by all users but I think it is the only option if you don't want an alpha channel and also want only day(night) data.

Yeah that’s what I want to say.

2023-01-23 11:48 UTC, yukaribbba commented
Anything else I can do to this PR? @mraspaud @pnuu @gerritholl

2023-01-23 11:58 UTC, mraspaud approved these changes
LGTM

2023-01-23 11:59 UTC, mraspaud commented
@yukaribbba thanks for this PR, it looks good to me. However, as @djhoese followed this more closely, I'd like to have his approval before merging this.

2023-01-23 12:05 UTC, yukaribbba commented
@mraspaud Okay.😊

2023-01-23 15:35 UTC, djhoese approved these changes
Looks good. There is one issue with rendering the docs which I think I've fixed in my other comment. I'll commit that in a second.

Otherwise, my only other concern is something I think you've made the right decision on: the coszen is a value between 0 and 1 so for a day-only case you might want different things masked out. There is the night region, the twilight/mixed region, and the day region. If I say `include_alpha=False` do I want the twilight region removed or should it stay in the image? I think it needs to stay in the image which is what I think you've done here. This way it can be overlayed with a night-only image later on and there is no gap in the middle between the two images.

Right?

2023-01-23 15:35 UTC, djhoese commented on satpy/composites/__init__.py
> +                                   (replaced with NaNs).
Documentation is failing with:

```
/lib/python3.10/site-packages/satpy/composites/__init__.py:docstring of satpy.composites.DayNightCompositor:22: ERROR: Unexpected indentation.
```

I think this should fix it:

```suggestion
            include_alpha (bool): This only affects the "day only" or "night only" result.
                                  True means an alpha band will be added to the output image for transparency.
                                  False means the output is a single-band image with undesired pixels being masked out
                                  (replaced with NaNs).
```

2023-01-23 16:25 UTC, yukaribbba commented
> If I say `include_alpha=False` do I want the twilight region removed or should it stay in the image? I think it needs to stay in the image which is what I think you've done here. This way it can be overlayed with a night-only image later on and there is no gap in the middle between the two images.
> 
Sure the twilight region will stay on the image. Here's a result for your case:
![image](https://user-images.githubusercontent.com/72339781/214091943-feef174c-97f4-4e3c-9bbd-99660d622291.png)

But, you may have noticed that this area seems to be a little darker since both images are fading there. So if you want a stacked image just simply use the default "day_and_night" and choose two normal composites.

2023-01-23 16:41 UTC, djhoese commented
> But, you may have noticed that this area seems to be a little darker since both images are fading there. So if you want a stacked image just simply use the default "day_and_night" and choose two normal composites.

Well see in my case (a possible future use, not currently doing this) would be having the individual masked day-only and night-only images and then in tiled image viewer (like https://geosphere.ssec.wisc.edu/) I would allow the user to switch the night image but keep the same day image. Generating all those combinations would not be a realistic option. I suppose what you're saying is that since these images would be "blending to black", they'll always have darker night-time transitions than they would if they were combined from the beginning (in satpy). Ya know, I'm OK with having the alpha channel in my images anyway so this probably isn't a realistic problem for me.

2023-01-23 16:50 UTC, yukaribbba commented
Also, talking about this made me think of #2288 . Now we may have a easier solution.

```
true_color_corr:
lim_low: 85
lim_high: 88
day_night: day_only
include_alpha: false

true_color_uncorr:
lim_low: 85
lim_high: 88
day_night: night_only
include_alpha: false

true_color_mix:
- true_color_corr
- true_color_uncorr
lim_low: 85
lim_high: 88
day_night: day_night
```

Considering there could be some unexpected noises on night side, this could be cleaner:

```
true_color_mix_cleaner:
- true_color_mix
lim_low: 85
lim_high: 88
day_night: day_only
include_alpha: false
```

I have tested this recipe and it’s just perfect for me.

2023-01-23 16:51 UTC, djhoese commented
CC @simonrp84 ^

2023-01-23 16:53 UTC, yukaribbba commented
> I suppose what you're saying is that since these images would be "blending to black", they'll always have darker night-time transitions than they would if they were combined from the beginning (in satpy).

Yep. That’s the point.

2023-01-23 16:54 UTC, djhoese commented
Let's merge this and if someone comes up with other use cases that need changes to this implementation we can make additional PRs. Thanks @yukaribbba for putting this together and working with all my requests.

2023-01-23 16:54 UTC, merged

2023-01-23 16:55 UTC, pnuu commented
> Well see in my case (a possible future use, not currently doing this) would be having the individual masked day-only and night-only images and then in tiled image viewer (like https://geosphere.ssec.wisc.edu/) I would allow the user to switch the night image but keep the same day image. Generating all those combinations would not be a realistic option.

Oooh, I need to think about this idea, too!

2023-01-23 16:58 UTC, yukaribbba commented
@djhoese @mraspaud Thanks for the help! 😁

2024-11-29 10:29 UTC, gerritholl commented
See #3003 for a continuation of this discussion.  I'm now trying to generate the day-only part of RGBs with the night part transparent but without an alpha layer.  I can see a use case replacing the night part by black for RGBs mixing solar and terrestrial channels or ratios / differences between solar channels.

2024-11-29 10:33 UTC, pnuu commented
Transparency won't happen without the alpha layer. The "other side" should be `fill_value` with `include_alpha: False`, though.

2024-11-29 10:54 UTC, gerritholl commented
Pixels set to `fill_value` should be 100% transparent in supporting viewers.

2024-11-29 10:58 UTC, pnuu commented
That depends also on the image format. But to be fully pedantic, the image won't have transparency :-)