Add initial support for EUMETSAT's climatological calibration
pytroll/satpy pull request #2375
Opened 2023-02-02 12:48 UTC by simonrp84

EUMETSAT are working on long-term calibration coefficients for SEVIRI, which will be available as external files specifying the gain and offset for each satellite over their lifetime.

This PR adds initial support for these calibration coefficients as an additional calibration method, `EUMCLIM`. Currently, I've only added support for the `native` reader, as this is the data format for historical images on the data store and eoportal. I will also add support to the HRIT and netCDF readers at a later point, as this should be reasonably straightforward.

This is a draft for now as I need to add the docs + tests.
 - [ ] Tests added 
 - [ ] Fully documented

2023-02-02 13:17 UTC, pnuu reviewed
Some initial comments inline.

2023-02-02 13:17 UTC, pnuu commented on satpy/readers/seviri_base.py
> +            for chan in coef_map.keys():
`.keys()` isn't needed.

2023-02-02 13:17 UTC, pnuu commented on satpy/readers/seviri_base.py
> +                        'IR_134': 'IR134'}
Move outside as a constant. `EUMCLIM_COEF_MAP` or something.

2023-02-02 13:17 UTC, pnuu commented on satpy/readers/seviri_l1b_native.py
> +            self.eumclim_cal_coef = {}
Set `self.eumclim_cal_coef = {}` by default so the `else` branch isn't needed.

2023-02-02 13:17 UTC, pnuu commented on satpy/readers/seviri_l1b_native.py
> +            tmp_dict = self.ext_calib_coefs
Could the `self.ext_calib_coefs` be set with the sorted EUMCLIM values already in the `if self.calib_mode == 'EUMCLIM` branch in `__init__()`? Then `tmp_dict` and the if/else wouldn't be needed.

2023-02-02 13:38 UTC, pnuu commented
pre-commit.ci autofix

2023-02-02 13:46 UTC, pnuu commented
pre-commit.ci run

2023-02-02 13:48 UTC, pnuu commented
pre-commit.ci autofix

2023-02-07 09:51 UTC, mraspaud requested changes
LGTM logic-wise, just some documentation about the new parameter missing, and maybe a link to the place to download/get some info about the calibration files?

2023-02-13 09:53 UTC, sfinkens reviewed
Oh, that's good news! Thanks for adding support for this.

I'm a bit concerned that the number of calibration options is getting too large. What if we delegate the loading of EUMCAL coefficients to the user? For example:

```python
from satpy.readers.seviri_base import load_eumcal_nc
eum_coefs = load_eumcal_nc(filename)
scene = Scene(..., ext_calib_coefs=eum_coefs)
```
And, if they wanted to merge them with other coefficients, provide a helper method:

```python
from satpy.readers.seviri_base import merge_coefs
merged_coefs = merge_coefs(other_coefs, eum_coefs)
```

Of course that would require the reader to be aware of time dependent coefficients, but that's a nice feature I think.

2023-02-13 09:53 UTC, sfinkens commented on satpy/tests/reader_tests/test_seviri_base.py
> +    def test_load_eumclim_nc_goodfile(self, make_dummy_ncdf):
This test could be simplified using a parametrization

```python
pytest.mark.parametrize(
    "timestamp,index_exp",
    [
        (datetime(2020, 1, 12, 15, 36), 0),
        (datetime(2020, 1, 12, 15, 46), 1),
        ...
)
def test_load_eumclim_nc_goodfile(self, make_dummy_ncdf, timestamp, index_exp):
    retval = load_eumclim_nc(make_dummy_ncdf, timestamp)
    np.testing.assert_allclose(retval['WV_073']['gain'], DUMMY_DATA['WV_073_gain'][index_exp])
    np.testing.assert_allclose(retval['IR_120']['offset'], DUMMY_DATA['IR_120_offset'][index_exp])
```

2023-02-13 09:53 UTC, sfinkens commented on satpy/tests/reader_tests/test_seviri_base.py
> +    print(fname)
Debugging leftover

2023-02-13 09:53 UTC, sfinkens commented on satpy/readers/seviri_base.py
> +            jul_idx = np.argmin(abs(jul_time - fid['julian_time']))
Can the index calculation be extracted to a separate method?

2026-06-11 08:08 UTC, closed without merging