VGAC decode the time variable
pytroll/satpy pull request #2595
Opened 2023-10-10 12:46 UTC by ninahakansson

Decode the time variable into a np.datetime64 variable. The time variable in VGAC need to be decoded in two steps. The time variable contains hours since proj_time0 for each scanline and the proj_time0 has the unit "days since 2010-01-01".

 - [ ] Tests added

2023-10-11 07:01 UTC, mraspaud requested changes
Ok, that's a messy datetime format they have in these files! Good job on sorting it out :)
Tests are missing obviously, but I also have a few comments/questions inline.

2023-10-11 07:01 UTC, mraspaud commented on satpy/readers/viirs_vgac_l1c_nc.py
> +            return data
So what does this mean? I the data readily formatted in some cases? Shouldn't we raise an error of the data doesn't have expected units instead?

2023-11-24 09:51 UTC, ninahakansson commented on satpy/readers/viirs_vgac_l1c_nc.py
> +                                     coords=data.coords, attrs={"long_name": "Scanline time"})
I think it needs unit first then you write it to file.

2024-01-18 08:32 UTC, mraspaud approved these changes
LGTM

2024-03-08 08:35 UTC, merged