Fix composites failing on non-aligned geolocation coordinates
pytroll/satpy pull request #2690
Opened 2023-12-14 20:20 UTC by djhoese

See #2668 for detailed discussion. Basically #2610 switched from the internal satpy base resampler to the pyresample base resampler class. This overall isn't a problem except for the pyresample base resample has a shortcut where it won't process an input if it detects that the target geometry is the same as the source geometry. In those cases it returns the original DataArray with no additional modification. This logically/theoretically shouldn't be a problem, but it reveals a larger issue.

When y and x coordinates are generated from different sources they may have very small differences due to floating point precision issues. So example an x and y that are a subset/slice of a larger pair of x/y arrays may be different than an x/y generated from a sliced/subset AreaDefinition of the same original area definition (again, look at my comments in the referenced issue).

This PR updates one part of Satpy to make these operations work as overall the resampler change revealed an existing issue that was previously being hidden. The composite base class now performs a call to `xarray.align` to make sure that input arrays are compatible, but for `y` and `x` coordinates it will re-assign them to match the first input. The docstring in the new method explains any concerns about this.

 - [x] Closes #2668 
 - [x] Tests added 
 - [x] Fully documented

2023-12-14 21:31 UTC, simonrp84 commented
Adding a note here to say that this fixes the problem I have been experiencing with cropping Himawari data:
```
scn = Scene(ifiles_l15, reader='ahi_hsd')
scn.load(['true_color_reproduction'])
scn2 = scn.crop(xy_bbox = bbox)
scn3 = scn2.resample(scn2.coarsest_area(), resampler='native', reduce_data=False)
scn3.save_datasets(base_dir=tod, writer='simple_image')
```

The above code fails on satpy's `main` but runs correctly with this PR.

@yufeizhu600 Maybe you can try this PR with the problems you were having with @strandgren's geocolor PR - guess the two PRs can be used together...somehow?

2023-12-15 02:48 UTC, yufeizhu600 commented
> @yufeizhu600 Maybe you can try this PR with the problems you were having with @strandgren's geocolor PR - guess the two PRs can be used together...somehow?
@simonrp84 , you tagged wrong person. :). I think you meant to tag @yukaribbba.

2023-12-15 03:18 UTC, yukaribbba commented
@yufeizhu600 @simonrp84 Thanks. I'll have a try.

2023-12-15 06:40 UTC, simonrp84 commented
Sorry for tagging the wrong person! Typed 'y' and went with githubs first suggestion 🙃 that's why you shouldn't code when tired,folks.

2023-12-15 08:01 UTC, mraspaud approved these changes
LGTM! I think it's good to merge as it is, I'm just wondering if we should have an new method called eg `unify_geo_coordinates` that groups `check_geolocation` and `align_geo_coordinates` into one place?

2023-12-15 10:05 UTC, ameraner requested changes
Indeed the fix works, thanks for implementing a nice solution so quickly! 

Unfortunately however, the NDVI-corrected True Color still fails; I took a look and it's because the `NDVIHybridGreen` calls `match_data_arrays` only on a subset of projectables, and then mixes these with the other unmatched projectables. This is fixed by 

```diff
diff --git a/satpy/composites/spectral.py b/satpy/composites/spectral.py
index 448d7cb..ba417ac 100644
--- a/satpy/composites/spectral.py
+++ b/satpy/composites/spectral.py
@@ -160,9 +160,9 @@ class NDVIHybridGreen(SpectralBlender):
         LOG.info(f"Applying NDVI-weighted hybrid-green correction with limits [{self.limits[0]}, "
                  f"{self.limits[1]}] and strength {self.strength}.")

-        ndvi_input = self.match_data_arrays([projectables[1], projectables[2]])
+        ndvi_input = self.match_data_arrays(projectables)

-        ndvi = (ndvi_input[1] - ndvi_input[0]) / (ndvi_input[1] + ndvi_input[0])
+        ndvi = (ndvi_input[2] - ndvi_input[1]) / (ndvi_input[2] + ndvi_input[1])

```
if you want you can include this in this PR, or I can make a quick separate one.

2023-12-15 14:48 UTC, djhoese commented
> I'm just wondering if we should have an new method called eg unify_geo_coordinates that groups check_geolocation and align_geo_coordinates into one place?

@mraspaud I had this same thought, but with drop_coordinates and align_geo_coordinates. So...maybe that's a sign that they should stay the way they are?

2023-12-15 14:52 UTC, merged