add the new variable name of cloud particle size of GOES-R L2 CPS product into the abi l2 reader config
pytroll/satpy pull request #2995
Opened 2024-11-21 16:26 UTC by yufeizhu600

NOAA has changed the variable name of `cloud particle size` from `PSD` to `CPS` in the  GOES-R ABI l2 `OR_ABI-L2-CPS*` product files on December 2023.   
source: [GOES-16 and GOES-18 Software Build PR.13.01.00 Implementation](https://www.ospo.noaa.gov/data/messages/2023/12/MSG_20231204_1914.html)

> Update data variable name in Cloud Particle Size product - Up to now, the Cloud Particle Size product produced by the Cloud Optical and Microphysical Properties (COMP) algorithm, has incorrectly listed its primary variable as “Particle Size Distribution” (PSD). This is being updated in this release to properly refer to the product as “Cloud Particle Size” (CPS), which will also make it consistent with its output filename (i.e. OR_ABI-L2-CPS*).   

This PR add the new variable name `CPS` into the config file of abi_l2_nc reader, so that it can read `CPS` variable from `OR_ABI-L2-CPS*` L2 product files.   
Configuration fro `PSD` variable has not been changed to ensure backward compatibility.

2024-11-21 19:39 UTC, djhoese requested changes
Could you maybe add a comment mentioning the name change and the date it took effect?

2024-11-22 18:37 UTC, yufeizhu600 commented
> Could you maybe add a comment mentioning the name change and the date it took effect?

Sure, I have updated the description above to include the time of change from NOAA's bulletin. And also added the first product file of each satellite scan section after the switch.

2024-11-22 18:58 UTC, djhoese commented
Sorry I meant in the YAML right above the new definition maybe?

2024-11-22 19:36 UTC, yufeizhu600 commented
> Sorry I meant in the YAML right above the new definition maybe?

OK, done.

2024-11-22 20:42 UTC, djhoese approved these changes

2024-11-22 20:44 UTC, merged